// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1TOCu30uJIZVxu0uVl1jY4K8qJeo2fCs',
    appId: '1:1073151505867:web:3ba12aa3d9c83cc4eb324e',
    messagingSenderId: '1073151505867',
    projectId: 'common-100a8',
    authDomain: 'common-100a8.firebaseapp.com',
    storageBucket: 'common-100a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmOkVuohIzTDm2gpkL5FW10oIuuYWbteI',
    appId: '1:1073151505867:android:230a19e3d3338ee8eb324e',
    messagingSenderId: '1073151505867',
    projectId: 'common-100a8',
    storageBucket: 'common-100a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0K0KHC8A07HJ0LpiuZxKKW3QnSBJ_aY',
    appId: '1:1073151505867:ios:653c2787aa50031ceb324e',
    messagingSenderId: '1073151505867',
    projectId: 'common-100a8',
    storageBucket: 'common-100a8.appspot.com',
    iosBundleId: 'com.example.advancedBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0K0KHC8A07HJ0LpiuZxKKW3QnSBJ_aY',
    appId: '1:1073151505867:ios:2536d6b95e838c4aeb324e',
    messagingSenderId: '1073151505867',
    projectId: 'common-100a8',
    storageBucket: 'common-100a8.appspot.com',
    iosBundleId: 'com.example.advancedBloc.RunnerTests',
  );
}
